version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
    - 5672:5672
    - 15672:15672
    env_file:
      - .development.env

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    env_file:
      - .development.env

    ports:
      - ${PORT}:${PORT}

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    depends_on:
      - rabbitmq

    command: npm run start:dev api

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    env_file:
      - .development.env


    networks:
      - postgres_auth

    links:
      - postgres_auth

    depends_on:
      - rabbitmq
      - postgres_auth
      - profile
      - api

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    command: npm run start:dev auth

  profile:
    build:
      context: .
      dockerfile: ./apps/profile/Dockerfile
      target: development

    env_file:
      - .development.env

    networks:
      - postgres_profile

    depends_on:
      - rabbitmq
      - postgres_profile
      - api

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    command: npm run start:dev profile

  postgres_auth:
    image: postgres
    container_name: postgres_auth
    env_file:
      - .development.env

    networks:
      - postgres_auth
    ports:
      - 5432:5432

    volumes:
      - ./initdb.d/auth.initdb.sql:/docker-entrypoint-initdb.d/auth.initdb.sql
      - ./auth_db/data:/var/lib/postgresql/data

  postgres_profile:
    image: postgres
    container_name: postgres_profile

    env_file:
      - .development.env
    
    networks:
      - postgres_profile
    ports:
      - 5431:5432

    volumes:
      - ./initdb.d/profile.initdb.sql:/docker-entrypoint-initdb.d/profile.initdb.sql
      - ./profile_db/data:/var/lib/postgresql/data

volumes:
  auth_db:
  profile_db:

networks:
  postgres_profile:
  postgres_auth: